# This is a Python template Makefile, do modification as you want
#
# Project:
# Author:
# Email :

HOST = 127.0.0.1
PYTHONPATH="$(shell printenv PYTHONPATH):$(PWD)"

## siamese experiments
run-1-siamese_exps:
	python ../src/training.py --quantization "nullhop" --seed 1 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-2-siamese_exps:
	python ../src/training.py --quantization "nullhop" --seed 2 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-3-siamese_exps:
	python ../src/training.py --quantization "nullhop" --seed 3 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-4-siamese_exps:
	python ../src/training.py --quantization "nullhop" --seed 4 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-5-siamese_exps:
	python ../src/training.py --quantization "nullhop" --seed 5 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-6-siamese_exps:
	python ../src/training.py --quantization "nullhop" --seed 6 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-7-siamese_exps:
	python ../src/training.py --quantization "nullhop" --seed 7 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-8-siamese_exps:
	python ../src/training.py --quantization "nullhop" --seed 8 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-9-siamese_exps:
	python ../src/training.py --quantization "nullhop" --seed 9 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-10-siamese_exps:
	python ../src/training.py --quantization "nullhop" --seed 10 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-11-siamese_exps:
	python ../src/training.py --quantization None --seed 1 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-12-siamese_exps:
	python ../src/training.py --quantization None --seed 2 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-13-siamese_exps:
	python ../src/training.py --quantization None --seed 3 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-14-siamese_exps:
	python ../src/training.py --quantization None --seed 4 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-15-siamese_exps:
	python ../src/training.py --quantization None --seed 5 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-16-siamese_exps:
	python ../src/training.py --quantization None --seed 6 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-17-siamese_exps:
	python ../src/training.py --quantization None --seed 7 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-18-siamese_exps:
	python ../src/training.py --quantization None --seed 8 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-19-siamese_exps:
	python ../src/training.py --quantization None --seed 9 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-20-siamese_exps:
	python ../src/training.py --quantization None --seed 10 --dataset "tiny-imagenet" --model "HorizontalNetworkV44" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
