# This is a Python template Makefile, do modification as you want
#
# Project:
# Author:
# Email :

HOST = 127.0.0.1
PYTHONPATH="$(shell printenv PYTHONPATH):$(PWD)"

## siamese experiments
run-1-siamese_exps:
	python ../src/training.py --num_shots 5 --seed 1 --dataset "tiny-imagenet" --model "HorizontalNetworkV5" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-2-siamese_exps:
	python ../src/training.py --num_shots 5 --seed 2 --dataset "tiny-imagenet" --model "HorizontalNetworkV5" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-3-siamese_exps:
	python ../src/training.py --num_shots 5 --seed 3 --dataset "tiny-imagenet" --model "HorizontalNetworkV5" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-4-siamese_exps:
	python ../src/training.py --num_shots 5 --seed 4 --dataset "tiny-imagenet" --model "HorizontalNetworkV5" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-5-siamese_exps:
	python ../src/training.py --num_shots 5 --seed 5 --dataset "tiny-imagenet" --model "HorizontalNetworkV5" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-6-siamese_exps:
	python ../src/training.py --num_shots 5 --seed 6 --dataset "tiny-imagenet" --model "HorizontalNetworkV5" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-7-siamese_exps:
	python ../src/training.py --num_shots 5 --seed 7 --dataset "tiny-imagenet" --model "HorizontalNetworkV5" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-8-siamese_exps:
	python ../src/training.py --num_shots 5 --seed 8 --dataset "tiny-imagenet" --model "HorizontalNetworkV5" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-9-siamese_exps:
	python ../src/training.py --num_shots 5 --seed 9 --dataset "tiny-imagenet" --model "HorizontalNetworkV5" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
run-10-siamese_exps:
	python ../src/training.py --num_shots 5 --seed 10 --dataset "tiny-imagenet" --model "HorizontalNetworkV5" --results_path "/scratch/jlungu/siamese_exps" --data_path "/data/jlungu/siamese_cluster_data_new"
