#!/bin/bash
#SBATCH --ntasks=1
#SBATCH -A delbruck.ini.uzh
#SBATCH --partition=vesta
#SBATCH --time=24:0:0
#SBATCH --mem-per-cpu=14000
#SBATCH --array=1-80
#SBATCH --gres gpu:Tesla-K80:1 --mem=14000
#SBATCH --output=./exp-logs/fconv-en2cn-run-%a.log
#SBATCH --error=./exp-logs/fconv-en2cn-run-%a.log

source activate siamese

cd $HOME/improved_siamese_JETCAS

make run-${SLURM_ARRAY_TASK_ID}-siamese_exps
