#!/bin/bash
#SBATCH --ntasks=1
#SBATCH -A delbruck.ini.uzh
#SBATCH --partition=vesta
#SBATCH --time=100:0:0
#SBATCH --mem-per-cpu=16000
#SBATCH --array=1-2
#SBATCH --gres gpu:Tesla-K80:1 --mem=16000
#SBATCH --output=/data/jlungu/exp-logs/fconv-en2cn-run-%a.log
#SBATCH --error=/data/jlungu/exp-logs/fconv-en2cn-run-%a.log

conda activate siamese_tf2
cd /data/jlungu/siamese_on_edge_tf2/tasks

make run-${SLURM_ARRAY_TASK_ID}-siamese_exps
